// Opens a clean, printable student report in a new window and triggers the
// browser print dialog (where it can be saved as PDF). No PDF library needed.
function esc(s) {
  return String(s == null ? '' : s).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
}

// Lightweight Markdown → HTML for printable handouts (headings, bold, lists,
// paragraphs). Good enough for a lesson plan or quiz the teacher prints out.
function mdToHtml(md) {
  const lines = String(md || '').split('\n');
  let html = '';
  let inList = false;
  const inline = (s) =>
    esc(s)
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/(^|[^*])\*([^*]+)\*/g, '$1<em>$2</em>')
      .replace(/`([^`]+)`/g, '<code>$1</code>');
  const closeList = () => {
    if (inList) {
      html += '</ul>';
      inList = false;
    }
  };
  for (const raw of lines) {
    const line = raw.trimEnd();
    const h = line.match(/^(#{1,6})\s+(.*)$/);
    const li = line.match(/^\s*[-*+]\s+(.*)$/);
    const ol = line.match(/^\s*\d+\.\s+(.*)$/);
    if (h) {
      closeList();
      const level = Math.min(h[1].length + 1, 6);
      html += `<h${level}>${inline(h[2])}</h${level}>`;
    } else if (li || ol) {
      if (!inList) {
        html += '<ul>';
        inList = true;
      }
      html += `<li>${inline((li || ol)[1])}</li>`;
    } else if (!line.trim()) {
      closeList();
    } else {
      closeList();
      html += `<p>${inline(line)}</p>`;
    }
  }
  closeList();
  return html;
}

// Open a clean, printable document (Markdown content) in a new window.
export function printDoc(title, markdown) {
  const date = new Date().toLocaleDateString();
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)} — MwanaAI</title>
<style>
  body{font-family:Arial,Helvetica,sans-serif;color:#1f2937;max-width:760px;margin:24px auto;padding:0 16px;line-height:1.5}
  h1{color:#c2410c;margin:0}
  h2{color:#9a3412;margin:22px 0 6px;border-bottom:1px solid #f1d5c4;padding-bottom:4px}
  h3,h4{margin:16px 0 4px}
  .muted{color:#6b7280;font-size:13px}
  ul{margin:6px 0 12px;padding-left:22px}
  li{margin:3px 0}
  code{background:#f3f4f6;padding:1px 4px;border-radius:4px;font-size:13px}
  button{margin-top:20px;background:#c2410c;color:#fff;border:none;padding:8px 16px;border-radius:8px;font-size:14px;cursor:pointer}
  @media print{button{display:none}}
</style></head><body>
  <h1>MwanaAI</h1>
  <p class="muted">${esc(title)} · ${date}</p>
  ${mdToHtml(markdown)}
  <p class="muted">Generated by MwanaAI — please review before teaching.</p>
  <button onclick="window.print()">Print / Save as PDF</button>
  <script>setTimeout(function(){window.print();},400);</script>
</body></html>`;
  const w = window.open('', '_blank');
  if (!w) {
    alert('Please allow pop-ups to print.');
    return;
  }
  w.document.write(html);
  w.document.close();
}

export function printStudentReport({
  name,
  email = '',
  level = '',
  quizzes = 0,
  avg = null,
  lessons = 0,
  subjectRows = [],
  results = [],
}) {
  const date = new Date().toLocaleDateString();

  const subjectHtml = subjectRows
    .map(
      (s) =>
        `<tr><td>${esc(s.name)}</td><td style="text-align:right">${s.avg}%</td><td style="text-align:right">${s.count}</td></tr>`
    )
    .join('');

  const historyHtml = results
    .slice(0, 30)
    .map(
      (r) =>
        `<tr><td>${esc(r.subjectLabel || r.subject || '')}</td><td>${
          r.createdAt ? new Date(r.createdAt).toLocaleDateString() : ''
        }</td><td style="text-align:right">${r.score}/${r.total} (${r.percentage}%)</td></tr>`
    )
    .join('');

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>MwanaAI Report — ${esc(name)}</title>
<style>
  body{font-family:Arial,Helvetica,sans-serif;color:#1f2937;max-width:720px;margin:24px auto;padding:0 16px}
  h1{color:#0284c7;margin:0}
  h3{margin:20px 0 6px}
  .muted{color:#6b7280;font-size:13px}
  table{width:100%;border-collapse:collapse;margin:6px 0 16px}
  th,td{padding:6px 8px;border-bottom:1px solid #e5e7eb;font-size:13px;text-align:left}
  .stats{display:flex;gap:12px;margin:16px 0}
  .stat{flex:1;text-align:center;border:1px solid #e5e7eb;border-radius:10px;padding:12px}
  .stat b{display:block;font-size:24px;color:#0284c7}
  button{margin-top:16px;background:#0284c7;color:#fff;border:none;padding:8px 16px;border-radius:8px;font-size:14px;cursor:pointer}
  @media print{button{display:none}}
</style></head><body>
  <h1>MwanaAI</h1>
  <p class="muted">Student progress report · ${date}</p>
  <h2 style="margin-bottom:0">${esc(name)}</h2>
  <p class="muted">${esc(email)}${level ? ' · ' + esc(level) : ''}</p>
  <div class="stats">
    <div class="stat"><b>${quizzes}</b>Quizzes</div>
    <div class="stat"><b>${avg == null ? '—' : avg + '%'}</b>Average</div>
    <div class="stat"><b>${lessons}</b>Lessons</div>
  </div>
  ${subjectHtml ? `<h3>By subject</h3><table><tr><th>Subject</th><th style="text-align:right">Average</th><th style="text-align:right">Quizzes</th></tr>${subjectHtml}</table>` : ''}
  ${historyHtml ? `<h3>Recent quizzes</h3><table><tr><th>Subject</th><th>Date</th><th style="text-align:right">Score</th></tr>${historyHtml}</table>` : ''}
  <p class="muted">Generated by MwanaAI</p>
  <button onclick="window.print()">Print / Save as PDF</button>
  <script>setTimeout(function(){window.print();},400);</script>
</body></html>`;

  const w = window.open('', '_blank');
  if (!w) {
    alert('Please allow pop-ups to print the report.');
    return;
  }
  w.document.write(html);
  w.document.close();
}
