// Opens a clean, printable student report in a new window and triggers the
// browser print dialog (where it can be saved as PDF). No PDF library needed.
function esc(s) {
  return String(s == null ? '' : s).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
}

export function printStudentReport({
  name,
  email = '',
  level = '',
  quizzes = 0,
  avg = null,
  lessons = 0,
  subjectRows = [],
  results = [],
}) {
  const date = new Date().toLocaleDateString();

  const subjectHtml = subjectRows
    .map(
      (s) =>
        `<tr><td>${esc(s.name)}</td><td style="text-align:right">${s.avg}%</td><td style="text-align:right">${s.count}</td></tr>`
    )
    .join('');

  const historyHtml = results
    .slice(0, 30)
    .map(
      (r) =>
        `<tr><td>${esc(r.subjectLabel || r.subject || '')}</td><td>${
          r.createdAt ? new Date(r.createdAt).toLocaleDateString() : ''
        }</td><td style="text-align:right">${r.score}/${r.total} (${r.percentage}%)</td></tr>`
    )
    .join('');

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>MwanaAI Report — ${esc(name)}</title>
<style>
  body{font-family:Arial,Helvetica,sans-serif;color:#1f2937;max-width:720px;margin:24px auto;padding:0 16px}
  h1{color:#0284c7;margin:0}
  h3{margin:20px 0 6px}
  .muted{color:#6b7280;font-size:13px}
  table{width:100%;border-collapse:collapse;margin:6px 0 16px}
  th,td{padding:6px 8px;border-bottom:1px solid #e5e7eb;font-size:13px;text-align:left}
  .stats{display:flex;gap:12px;margin:16px 0}
  .stat{flex:1;text-align:center;border:1px solid #e5e7eb;border-radius:10px;padding:12px}
  .stat b{display:block;font-size:24px;color:#0284c7}
  button{margin-top:16px;background:#0284c7;color:#fff;border:none;padding:8px 16px;border-radius:8px;font-size:14px;cursor:pointer}
  @media print{button{display:none}}
</style></head><body>
  <h1>MwanaAI</h1>
  <p class="muted">Student progress report · ${date}</p>
  <h2 style="margin-bottom:0">${esc(name)}</h2>
  <p class="muted">${esc(email)}${level ? ' · ' + esc(level) : ''}</p>
  <div class="stats">
    <div class="stat"><b>${quizzes}</b>Quizzes</div>
    <div class="stat"><b>${avg == null ? '—' : avg + '%'}</b>Average</div>
    <div class="stat"><b>${lessons}</b>Lessons</div>
  </div>
  ${subjectHtml ? `<h3>By subject</h3><table><tr><th>Subject</th><th style="text-align:right">Average</th><th style="text-align:right">Quizzes</th></tr>${subjectHtml}</table>` : ''}
  ${historyHtml ? `<h3>Recent quizzes</h3><table><tr><th>Subject</th><th>Date</th><th style="text-align:right">Score</th></tr>${historyHtml}</table>` : ''}
  <p class="muted">Generated by MwanaAI</p>
  <button onclick="window.print()">Print / Save as PDF</button>
  <script>setTimeout(function(){window.print();},400);</script>
</body></html>`;

  const w = window.open('', '_blank');
  if (!w) {
    alert('Please allow pop-ups to print the report.');
    return;
  }
  w.document.write(html);
  w.document.close();
}
